[package]
name = "bandstand-synth"
description = "Sample playback, voices and DSP for Bandstand."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints.rust]
missing_docs = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"

[dependencies]
memmap2 = "0.9.11"
