// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioDevice dco_decode_audio_device(dynamic raw);

  @protected
  AudioStreamRequest dco_decode_audio_stream_request(dynamic raw);

  @protected
  AudioStreamStatus dco_decode_audio_stream_status(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AudioStreamRequest dco_decode_box_autoadd_audio_stream_request(dynamic raw);

  @protected
  AudioStreamStatus dco_decode_box_autoadd_audio_stream_status(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<AudioDevice> dco_decode_list_audio_device(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TempoMarker> dco_decode_list_tempo_marker(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AudioStreamStatus? dco_decode_opt_box_autoadd_audio_stream_status(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  TempoMarker dco_decode_tempo_marker(dynamic raw);

  @protected
  TrackInfo dco_decode_track_info(dynamic raw);

  @protected
  TransportPosition dco_decode_transport_position(dynamic raw);

  @protected
  TransportState dco_decode_transport_state(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioDevice sse_decode_audio_device(SseDeserializer deserializer);

  @protected
  AudioStreamRequest sse_decode_audio_stream_request(
    SseDeserializer deserializer,
  );

  @protected
  AudioStreamStatus sse_decode_audio_stream_status(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AudioStreamRequest sse_decode_box_autoadd_audio_stream_request(
    SseDeserializer deserializer,
  );

  @protected
  AudioStreamStatus sse_decode_box_autoadd_audio_stream_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<AudioDevice> sse_decode_list_audio_device(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TempoMarker> sse_decode_list_tempo_marker(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AudioStreamStatus? sse_decode_opt_box_autoadd_audio_stream_status(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  TempoMarker sse_decode_tempo_marker(SseDeserializer deserializer);

  @protected
  TrackInfo sse_decode_track_info(SseDeserializer deserializer);

  @protected
  TransportPosition sse_decode_transport_position(SseDeserializer deserializer);

  @protected
  TransportState sse_decode_transport_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_device(AudioDevice self, SseSerializer serializer);

  @protected
  void sse_encode_audio_stream_request(
    AudioStreamRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_stream_status(
    AudioStreamStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_audio_stream_request(
    AudioStreamRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_audio_stream_status(
    AudioStreamStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_device(
    List<AudioDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tempo_marker(
    List<TempoMarker> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_audio_stream_status(
    AudioStreamStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_tempo_marker(TempoMarker self, SseSerializer serializer);

  @protected
  void sse_encode_track_info(TrackInfo self, SseSerializer serializer);

  @protected
  void sse_encode_transport_position(
    TransportPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_state(
    TransportState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
