// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1418209397;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_bandstand',
        ioDirectory: '../rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<AudioDevice>> crateApiAudioAudioDevices();

  Future<AudioStreamStatus> crateApiAudioAudioStart({
    required AudioStreamRequest request,
  });

  Future<AudioStreamStatus?> crateApiAudioAudioStatus();

  Future<void> crateApiAudioAudioStop();

  Future<AudioStreamRequest> crateApiAudioAudioStreamRequestDefault();

  Future<void> crateApiInitApp();

  BigInt crateApiAudioMonotonicNowNs();

  Future<TrackInfo> crateApiAudioPlayerLoad({required String path});

  Future<void> crateApiAudioPlayerSetChannelMix({
    required double leftFromLeft,
    required double leftFromRight,
    required double rightFromLeft,
    required double rightFromRight,
  });

  Future<void> crateApiAudioPlayerUnload();

  Future<void> crateApiAudioSetMasterGain({required double gain});

  Future<void> crateApiAudioSetTestTone({
    required bool enabled,
    required double frequencyHz,
    required double amplitude,
  });

  Future<void> crateApiAudioTransportPause();

  Future<void> crateApiAudioTransportPlay();

  TransportPosition crateApiAudioTransportPosition();

  Future<void> crateApiAudioTransportSeek({required double tick});

  Future<void> crateApiAudioTransportSetLoop({
    required BigInt startTick,
    required BigInt endTick,
    required bool enabled,
  });

  Future<void> crateApiAudioTransportSetTempo({required double bpm});

  Future<void> crateApiAudioTransportSetTempoMap({
    required int ppq,
    required List<TempoMarker> markers,
  });

  Future<void> crateApiAudioTransportStop();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<AudioDevice>> crateApiAudioAudioDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_device,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAudioAudioDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioDevicesConstMeta =>
      const TaskConstMeta(debugName: "audio_devices", argNames: []);

  @override
  Future<AudioStreamStatus> crateApiAudioAudioStart({
    required AudioStreamRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_audio_stream_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_audio_stream_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAudioAudioStartConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioStartConstMeta =>
      const TaskConstMeta(debugName: "audio_start", argNames: ["request"]);

  @override
  Future<AudioStreamStatus?> crateApiAudioAudioStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_audio_stream_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioAudioStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioStatusConstMeta =>
      const TaskConstMeta(debugName: "audio_status", argNames: []);

  @override
  Future<void> crateApiAudioAudioStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioAudioStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioStopConstMeta =>
      const TaskConstMeta(debugName: "audio_stop", argNames: []);

  @override
  Future<AudioStreamRequest> crateApiAudioAudioStreamRequestDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_audio_stream_request,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioAudioStreamRequestDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioStreamRequestDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "audio_stream_request_default",
        argNames: [],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  BigInt crateApiAudioMonotonicNowNs() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioMonotonicNowNsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioMonotonicNowNsConstMeta =>
      const TaskConstMeta(debugName: "monotonic_now_ns", argNames: []);

  @override
  Future<TrackInfo> crateApiAudioPlayerLoad({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAudioPlayerLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioPlayerLoadConstMeta =>
      const TaskConstMeta(debugName: "player_load", argNames: ["path"]);

  @override
  Future<void> crateApiAudioPlayerSetChannelMix({
    required double leftFromLeft,
    required double leftFromRight,
    required double rightFromLeft,
    required double rightFromRight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(leftFromLeft, serializer);
          sse_encode_f_32(leftFromRight, serializer);
          sse_encode_f_32(rightFromLeft, serializer);
          sse_encode_f_32(rightFromRight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioPlayerSetChannelMixConstMeta,
        argValues: [leftFromLeft, leftFromRight, rightFromLeft, rightFromRight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioPlayerSetChannelMixConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_channel_mix",
        argNames: [
          "leftFromLeft",
          "leftFromRight",
          "rightFromLeft",
          "rightFromRight",
        ],
      );

  @override
  Future<void> crateApiAudioPlayerUnload() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioPlayerUnloadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioPlayerUnloadConstMeta =>
      const TaskConstMeta(debugName: "player_unload", argNames: []);

  @override
  Future<void> crateApiAudioSetMasterGain({required double gain}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(gain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioSetMasterGainConstMeta,
        argValues: [gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioSetMasterGainConstMeta =>
      const TaskConstMeta(debugName: "set_master_gain", argNames: ["gain"]);

  @override
  Future<void> crateApiAudioSetTestTone({
    required bool enabled,
    required double frequencyHz,
    required double amplitude,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          sse_encode_f_32(frequencyHz, serializer);
          sse_encode_f_32(amplitude, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioSetTestToneConstMeta,
        argValues: [enabled, frequencyHz, amplitude],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioSetTestToneConstMeta => const TaskConstMeta(
    debugName: "set_test_tone",
    argNames: ["enabled", "frequencyHz", "amplitude"],
  );

  @override
  Future<void> crateApiAudioTransportPause() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioTransportPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportPauseConstMeta =>
      const TaskConstMeta(debugName: "transport_pause", argNames: []);

  @override
  Future<void> crateApiAudioTransportPlay() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioTransportPlayConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportPlayConstMeta =>
      const TaskConstMeta(debugName: "transport_play", argNames: []);

  @override
  TransportPosition crateApiAudioTransportPosition() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transport_position,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioTransportPositionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportPositionConstMeta =>
      const TaskConstMeta(debugName: "transport_position", argNames: []);

  @override
  Future<void> crateApiAudioTransportSeek({required double tick}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(tick, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioTransportSeekConstMeta,
        argValues: [tick],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportSeekConstMeta =>
      const TaskConstMeta(debugName: "transport_seek", argNames: ["tick"]);

  @override
  Future<void> crateApiAudioTransportSetLoop({
    required BigInt startTick,
    required BigInt endTick,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(startTick, serializer);
          sse_encode_u_64(endTick, serializer);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioTransportSetLoopConstMeta,
        argValues: [startTick, endTick, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportSetLoopConstMeta =>
      const TaskConstMeta(
        debugName: "transport_set_loop",
        argNames: ["startTick", "endTick", "enabled"],
      );

  @override
  Future<void> crateApiAudioTransportSetTempo({required double bpm}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(bpm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAudioTransportSetTempoConstMeta,
        argValues: [bpm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportSetTempoConstMeta =>
      const TaskConstMeta(debugName: "transport_set_tempo", argNames: ["bpm"]);

  @override
  Future<void> crateApiAudioTransportSetTempoMap({
    required int ppq,
    required List<TempoMarker> markers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(ppq, serializer);
          sse_encode_list_tempo_marker(markers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAudioTransportSetTempoMapConstMeta,
        argValues: [ppq, markers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportSetTempoMapConstMeta =>
      const TaskConstMeta(
        debugName: "transport_set_tempo_map",
        argNames: ["ppq", "markers"],
      );

  @override
  Future<void> crateApiAudioTransportStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioTransportStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTransportStopConstMeta =>
      const TaskConstMeta(debugName: "transport_stop", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioDevice dco_decode_audio_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AudioDevice(
      name: dco_decode_String(arr[0]),
      isDefault: dco_decode_bool(arr[1]),
    );
  }

  @protected
  AudioStreamRequest dco_decode_audio_stream_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AudioStreamRequest(
      deviceName: dco_decode_opt_String(arr[0]),
      sampleRate: dco_decode_opt_box_autoadd_u_32(arr[1]),
      bufferFrames: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  AudioStreamStatus dco_decode_audio_stream_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return AudioStreamStatus(
      deviceName: dco_decode_String(arr[0]),
      sampleRate: dco_decode_u_32(arr[1]),
      channels: dco_decode_u_16(arr[2]),
      bufferFrames: dco_decode_opt_box_autoadd_u_32(arr[3]),
      sampleFormat: dco_decode_String(arr[4]),
      errorCount: dco_decode_u_64(arr[5]),
      blockCount: dco_decode_u_64(arr[6]),
      frameCount: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AudioStreamRequest dco_decode_box_autoadd_audio_stream_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_audio_stream_request(raw);
  }

  @protected
  AudioStreamStatus dco_decode_box_autoadd_audio_stream_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_audio_stream_status(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AudioDevice> dco_decode_list_audio_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_device).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TempoMarker> dco_decode_list_tempo_marker(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tempo_marker).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AudioStreamStatus? dco_decode_opt_box_autoadd_audio_stream_status(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_audio_stream_status(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  TempoMarker dco_decode_tempo_marker(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TempoMarker(
      tick: dco_decode_u_64(arr[0]),
      bpm: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  TrackInfo dco_decode_track_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TrackInfo(
      durationMs: dco_decode_u_64(arr[0]),
      sampleRate: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  TransportPosition dco_decode_transport_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return TransportPosition(
      tick: dco_decode_f_64(arr[0]),
      hostTimeNs: dco_decode_u_64(arr[1]),
      readAtNs: dco_decode_u_64(arr[2]),
      state: dco_decode_transport_state(arr[3]),
      loopGeneration: dco_decode_u_32(arr[4]),
      ticksPerNanosecond: dco_decode_f_64(arr[5]),
      bpm: dco_decode_f_64(arr[6]),
      ppq: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  TransportState dco_decode_transport_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransportState.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioDevice sse_decode_audio_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_isDefault = sse_decode_bool(deserializer);
    return AudioDevice(name: var_name, isDefault: var_isDefault);
  }

  @protected
  AudioStreamRequest sse_decode_audio_stream_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceName = sse_decode_opt_String(deserializer);
    var var_sampleRate = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_bufferFrames = sse_decode_opt_box_autoadd_u_32(deserializer);
    return AudioStreamRequest(
      deviceName: var_deviceName,
      sampleRate: var_sampleRate,
      bufferFrames: var_bufferFrames,
    );
  }

  @protected
  AudioStreamStatus sse_decode_audio_stream_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceName = sse_decode_String(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    var var_bufferFrames = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_sampleFormat = sse_decode_String(deserializer);
    var var_errorCount = sse_decode_u_64(deserializer);
    var var_blockCount = sse_decode_u_64(deserializer);
    var var_frameCount = sse_decode_u_64(deserializer);
    return AudioStreamStatus(
      deviceName: var_deviceName,
      sampleRate: var_sampleRate,
      channels: var_channels,
      bufferFrames: var_bufferFrames,
      sampleFormat: var_sampleFormat,
      errorCount: var_errorCount,
      blockCount: var_blockCount,
      frameCount: var_frameCount,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AudioStreamRequest sse_decode_box_autoadd_audio_stream_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_audio_stream_request(deserializer));
  }

  @protected
  AudioStreamStatus sse_decode_box_autoadd_audio_stream_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_audio_stream_status(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<AudioDevice> sse_decode_list_audio_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_device(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TempoMarker> sse_decode_list_tempo_marker(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TempoMarker>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tempo_marker(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AudioStreamStatus? sse_decode_opt_box_autoadd_audio_stream_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_audio_stream_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TempoMarker sse_decode_tempo_marker(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tick = sse_decode_u_64(deserializer);
    var var_bpm = sse_decode_f_64(deserializer);
    return TempoMarker(tick: var_tick, bpm: var_bpm);
  }

  @protected
  TrackInfo sse_decode_track_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    return TrackInfo(durationMs: var_durationMs, sampleRate: var_sampleRate);
  }

  @protected
  TransportPosition sse_decode_transport_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tick = sse_decode_f_64(deserializer);
    var var_hostTimeNs = sse_decode_u_64(deserializer);
    var var_readAtNs = sse_decode_u_64(deserializer);
    var var_state = sse_decode_transport_state(deserializer);
    var var_loopGeneration = sse_decode_u_32(deserializer);
    var var_ticksPerNanosecond = sse_decode_f_64(deserializer);
    var var_bpm = sse_decode_f_64(deserializer);
    var var_ppq = sse_decode_u_32(deserializer);
    return TransportPosition(
      tick: var_tick,
      hostTimeNs: var_hostTimeNs,
      readAtNs: var_readAtNs,
      state: var_state,
      loopGeneration: var_loopGeneration,
      ticksPerNanosecond: var_ticksPerNanosecond,
      bpm: var_bpm,
      ppq: var_ppq,
    );
  }

  @protected
  TransportState sse_decode_transport_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransportState.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_device(AudioDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDefault, serializer);
  }

  @protected
  void sse_encode_audio_stream_request(
    AudioStreamRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.deviceName, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sampleRate, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bufferFrames, serializer);
  }

  @protected
  void sse_encode_audio_stream_status(
    AudioStreamStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceName, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bufferFrames, serializer);
    sse_encode_String(self.sampleFormat, serializer);
    sse_encode_u_64(self.errorCount, serializer);
    sse_encode_u_64(self.blockCount, serializer);
    sse_encode_u_64(self.frameCount, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_audio_stream_request(
    AudioStreamRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_audio_stream_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_audio_stream_status(
    AudioStreamStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_audio_stream_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_audio_device(
    List<AudioDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_tempo_marker(
    List<TempoMarker> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tempo_marker(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_audio_stream_status(
    AudioStreamStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_audio_stream_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_tempo_marker(TempoMarker self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.tick, serializer);
    sse_encode_f_64(self.bpm, serializer);
  }

  @protected
  void sse_encode_track_info(TrackInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
  }

  @protected
  void sse_encode_transport_position(
    TransportPosition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.tick, serializer);
    sse_encode_u_64(self.hostTimeNs, serializer);
    sse_encode_u_64(self.readAtNs, serializer);
    sse_encode_transport_state(self.state, serializer);
    sse_encode_u_32(self.loopGeneration, serializer);
    sse_encode_f_64(self.ticksPerNanosecond, serializer);
    sse_encode_f_64(self.bpm, serializer);
    sse_encode_u_32(self.ppq, serializer);
  }

  @protected
  void sse_encode_transport_state(
    TransportState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
