// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_timed`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// The output devices the platform offers.
///
/// # Errors
/// Returns a message if the platform cannot be queried.
Future<List<AudioDevice>> audioDevices() =>
    RustLib.instance.api.crateApiAudioAudioDevices();

/// Open (or reopen) the output stream.
///
/// # Errors
/// Returns a message if the device cannot be opened.
Future<AudioStreamStatus> audioStart({required AudioStreamRequest request}) =>
    RustLib.instance.api.crateApiAudioAudioStart(request: request);

/// Close the output stream.
Future<void> audioStop() => RustLib.instance.api.crateApiAudioAudioStop();

/// The state of the stream currently open, or `None` if there is none.
Future<AudioStreamStatus?> audioStatus() =>
    RustLib.instance.api.crateApiAudioAudioStatus();

/// Switch the reference test tone on or off, and set its frequency and gain.
///
/// `amplitude` is linear gain in `0.0..=1.0`; `frequency_hz` is clamped to the
/// audible range.
Future<void> setTestTone({
  required bool enabled,
  required double frequencyHz,
  required double amplitude,
}) => RustLib.instance.api.crateApiAudioSetTestTone(
  enabled: enabled,
  frequencyHz: frequencyHz,
  amplitude: amplitude,
);

/// Start playing from the current position.
Future<void> transportPlay() =>
    RustLib.instance.api.crateApiAudioTransportPlay();

/// Stop advancing, holding the playhead where it is.
Future<void> transportPause() =>
    RustLib.instance.api.crateApiAudioTransportPause();

/// Stop and return to the stop anchor.
Future<void> transportStop() =>
    RustLib.instance.api.crateApiAudioTransportStop();

/// Move the playhead.
Future<void> transportSeek({required double tick}) =>
    RustLib.instance.api.crateApiAudioTransportSeek(tick: tick);

/// Set the loop region, in ticks.
Future<void> transportSetLoop({
  required BigInt startTick,
  required BigInt endTick,
  required bool enabled,
}) => RustLib.instance.api.crateApiAudioTransportSetLoop(
  startTick: startTick,
  endTick: endTick,
  enabled: enabled,
);

/// Replace the whole tempo map.
///
/// # Errors
/// Returns a message if the markers are empty, out of order, or carry a tempo
/// outside 10–400 bpm.
Future<void> transportSetTempoMap({
  required int ppq,
  required List<TempoMarker> markers,
}) => RustLib.instance.api.crateApiAudioTransportSetTempoMap(
  ppq: ppq,
  markers: markers,
);

/// Set a single constant tempo, keeping the current resolution.
///
/// # Errors
/// Returns a message if `bpm` is outside 10–400.
Future<void> transportSetTempo({required double bpm}) =>
    RustLib.instance.api.crateApiAudioTransportSetTempo(bpm: bpm);

/// Read the playhead. Cheap enough to call once per rendered frame.
TransportPosition transportPosition() =>
    RustLib.instance.api.crateApiAudioTransportPosition();

/// Bandstand's monotonic clock, in nanoseconds.
///
/// The same clock `TransportPosition::host_time_ns` is expressed in.
BigInt monotonicNowNs() => RustLib.instance.api.crateApiAudioMonotonicNowNs();

/// Load a SoundFont (§3, §7.2).
///
/// Reading and mapping happen off the audio thread; the audio thread only ever
/// takes the finished bank.
///
/// # Errors
/// Returns a message if the file is not a SoundFont this build can read.
Future<SoundBankInfo> loadSoundbank({required String path}) =>
    RustLib.instance.api.crateApiAudioLoadSoundbank(path: path);

/// Unload the bank, so nothing plays.
Future<void> unloadSoundbank() =>
    RustLib.instance.api.crateApiAudioUnloadSoundbank();

/// The bank currently loaded, if any.
Future<SoundBankInfo?> loadedSoundbank() =>
    RustLib.instance.api.crateApiAudioLoadedSoundbank();

/// Hand the audio thread a whole sequence to play (§3).
///
/// Replaces whatever was there. Notes sounding from the old sequence are let
/// go, so nothing hangs.
///
/// # Errors
/// Returns a message if the tempo map is not one the transport accepts.
Future<void> loadSequence({
  required List<MidiEvent> events,
  required int ppq,
  required BigInt lengthTicks,
  required List<TempoMarker> tempoMarkers,
}) => RustLib.instance.api.crateApiAudioLoadSequence(
  events: events,
  ppq: ppq,
  lengthTicks: lengthTicks,
  tempoMarkers: tempoMarkers,
);

/// Forget the sequence, so nothing plays.
Future<void> clearSequence() =>
    RustLib.instance.api.crateApiAudioClearSequence();

/// How many events are loaded, and how long they last in ticks.
SequenceStatus sequenceStatus() =>
    RustLib.instance.api.crateApiAudioSequenceStatus();

/// Set a channel's level, position and mute (§3).
Future<void> setChannelMix({
  required int channel,
  required double volume,
  required double pan,
  required bool muted,
}) => RustLib.instance.api.crateApiAudioSetChannelMix(
  channel: channel,
  volume: volume,
  pan: pan,
  muted: muted,
);

/// Set the master level.
Future<void> setMasterGain({required double gain}) =>
    RustLib.instance.api.crateApiAudioSetMasterGain(gain: gain);

/// Stop every note at once, without moving the playhead.
Future<void> allNotesOff() => RustLib.instance.api.crateApiAudioAllNotesOff();

/// Render the loaded sequence to a WAV file (§3, §5.3).
///
/// Runs as fast as the machine allows — there is no device and no clock.
///
/// # Errors
/// Returns a message if there is no bank, no sequence, or the file cannot be
/// written.
Future<RenderResult> renderOffline({
  required String path,
  required int sampleRate,
}) => RustLib.instance.api.crateApiAudioRenderOffline(
  path: path,
  sampleRate: sampleRate,
);

/// An output device the user can choose.
class AudioDevice {
  /// Backend name; also the key used to reopen the device.
  final String name;

  /// Whether this is the system default output.
  final bool isDefault;

  const AudioDevice({required this.name, required this.isDefault});

  @override
  int get hashCode => name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDefault == other.isDefault;
}

/// What to ask the platform for when opening a stream.
class AudioStreamRequest {
  /// Device name, or `None` for the system default.
  final String? deviceName;

  /// Sample rate to request, or `None` to let Bandstand prefer 48 kHz.
  final int? sampleRate;

  /// Buffer size in frames, or `None` for Bandstand's default of 256.
  final int? bufferFrames;

  const AudioStreamRequest({
    this.deviceName,
    this.sampleRate,
    this.bufferFrames,
  });

  static Future<AudioStreamRequest> default_() =>
      RustLib.instance.api.crateApiAudioAudioStreamRequestDefault();

  @override
  int get hashCode =>
      deviceName.hashCode ^ sampleRate.hashCode ^ bufferFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioStreamRequest &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          sampleRate == other.sampleRate &&
          bufferFrames == other.bufferFrames;
}

/// What the platform actually gave us.
class AudioStreamStatus {
  /// Device the stream is running on.
  final String deviceName;

  /// Negotiated sample rate.
  final int sampleRate;

  /// Negotiated channel count.
  final int channels;

  /// Negotiated buffer size in frames, if the backend fixed one.
  final int? bufferFrames;

  /// The device's native sample format.
  final String sampleFormat;

  /// Backend errors since the stream opened. Non-zero means audio dropped.
  final BigInt errorCount;

  /// Audio blocks rendered since the stream opened.
  final BigInt blockCount;

  /// Frames rendered since the stream opened.
  final BigInt frameCount;

  const AudioStreamStatus({
    required this.deviceName,
    required this.sampleRate,
    required this.channels,
    this.bufferFrames,
    required this.sampleFormat,
    required this.errorCount,
    required this.blockCount,
    required this.frameCount,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bufferFrames.hashCode ^
      sampleFormat.hashCode ^
      errorCount.hashCode ^
      blockCount.hashCode ^
      frameCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioStreamStatus &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bufferFrames == other.bufferFrames &&
          sampleFormat == other.sampleFormat &&
          errorCount == other.errorCount &&
          blockCount == other.blockCount &&
          frameCount == other.frameCount;
}

/// One event in a sequence, as Dart sends it.
///
/// Deliberately flat and made only of numbers: this crosses the FFI boundary
/// tens of thousands of times for one song, and a shape with strings or
/// options in it would cost more to marshal than to play.
class MidiEvent {
  /// Where it happens, in ticks.
  final BigInt tick;

  /// Which MIDI channel, 0–15.
  final int channel;

  /// What it does.
  final MidiEventKind kind;

  /// The key, for notes; the program, for a program change.
  final int data1;

  /// The velocity, for notes; the bank, for a program change; the value, for
  /// a controller.
  final int data2;

  const MidiEvent({
    required this.tick,
    required this.channel,
    required this.kind,
    required this.data1,
    required this.data2,
  });

  @override
  int get hashCode =>
      tick.hashCode ^
      channel.hashCode ^
      kind.hashCode ^
      data1.hashCode ^
      data2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MidiEvent &&
          runtimeType == other.runtimeType &&
          tick == other.tick &&
          channel == other.channel &&
          kind == other.kind &&
          data1 == other.data1 &&
          data2 == other.data2;
}

/// What an event does. Mirrors the sequencer's own vocabulary.
enum MidiEventKind {
  /// Start a note.
  noteOn,

  /// Let a note go.
  noteOff,

  /// Select a sound.
  program,

  /// Set the channel volume, 0–127 in `value`.
  volume,

  /// Set the channel pan, 0–127 in `value`, 64 being centre.
  pan,

  /// Set the channel expression, 0–127 in `value`.
  expression,

  /// Put the sustain pedal down (`value` above 63) or up.
  sustain,

  /// Bend the pitch, 0–16383 in `value`, 8192 being centre.
  pitchBend,

  /// Let every note on the channel go.
  allNotesOff,
}

/// What a bounce produced.
class RenderResult {
  /// How many frames were written.
  final BigInt frames;

  /// How long the file lasts, in seconds.
  final double seconds;

  /// How many samples clipped. Non-zero means the mix was too loud.
  final BigInt clippedSamples;

  const RenderResult({
    required this.frames,
    required this.seconds,
    required this.clippedSamples,
  });

  @override
  int get hashCode =>
      frames.hashCode ^ seconds.hashCode ^ clippedSamples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderResult &&
          runtimeType == other.runtimeType &&
          frames == other.frames &&
          seconds == other.seconds &&
          clippedSamples == other.clippedSamples;
}

/// What is loaded.
class SequenceStatus {
  /// How many events.
  final int eventCount;

  /// How long they last, in ticks.
  final BigInt lengthTicks;

  const SequenceStatus({required this.eventCount, required this.lengthTicks});

  @override
  int get hashCode => eventCount.hashCode ^ lengthTicks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SequenceStatus &&
          runtimeType == other.runtimeType &&
          eventCount == other.eventCount &&
          lengthTicks == other.lengthTicks;
}

/// A loaded soundbank, as the UI shows it.
class SoundBankInfo {
  /// Where it came from.
  final String path;

  /// Its name, from the file.
  final String name;

  /// How many presets it has.
  final int presetCount;

  /// How many samples it has.
  final int sampleCount;

  const SoundBankInfo({
    required this.path,
    required this.name,
    required this.presetCount,
    required this.sampleCount,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      presetCount.hashCode ^
      sampleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoundBankInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          presetCount == other.presetCount &&
          sampleCount == other.sampleCount;
}

/// A tempo marker: from `tick` onwards, the tempo is `bpm`.
class TempoMarker {
  /// Position in ticks.
  final BigInt tick;

  /// Beats (quarter notes) per minute.
  final double bpm;

  const TempoMarker({required this.tick, required this.bpm});

  @override
  int get hashCode => tick.hashCode ^ bpm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TempoMarker &&
          runtimeType == other.runtimeType &&
          tick == other.tick &&
          bpm == other.bpm;
}

/// A coherent read of the playhead, for the UI to extrapolate from.
///
/// This is the shared-atomic readback of §3: no callback, no message, just a
/// direct read of the cell the audio thread publishes into once per block.
class TransportPosition {
  /// Playhead in ticks when the audio thread published.
  final double tick;

  /// Monotonic nanoseconds at which the published block reaches the speakers.
  final BigInt hostTimeNs;

  /// Monotonic nanoseconds at the moment of this read, so Dart can compute
  /// the elapsed time without a second call.
  final BigInt readAtNs;

  /// Transport state.
  final TransportState state;

  /// Increments on every loop wrap.
  final int loopGeneration;

  /// Ticks per nanosecond at `tick`, for extrapolation.
  final double ticksPerNanosecond;

  /// Tempo in effect at `tick`.
  final double bpm;

  /// Ticks per quarter note.
  final int ppq;

  const TransportPosition({
    required this.tick,
    required this.hostTimeNs,
    required this.readAtNs,
    required this.state,
    required this.loopGeneration,
    required this.ticksPerNanosecond,
    required this.bpm,
    required this.ppq,
  });

  @override
  int get hashCode =>
      tick.hashCode ^
      hostTimeNs.hashCode ^
      readAtNs.hashCode ^
      state.hashCode ^
      loopGeneration.hashCode ^
      ticksPerNanosecond.hashCode ^
      bpm.hashCode ^
      ppq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportPosition &&
          runtimeType == other.runtimeType &&
          tick == other.tick &&
          hostTimeNs == other.hostTimeNs &&
          readAtNs == other.readAtNs &&
          state == other.state &&
          loopGeneration == other.loopGeneration &&
          ticksPerNanosecond == other.ticksPerNanosecond &&
          bpm == other.bpm &&
          ppq == other.ppq;
}

/// What the transport is doing.
enum TransportState {
  /// Not playing; playhead parked at the stop anchor.
  stopped,

  /// Not playing; playhead held where it was.
  paused,

  /// Playing.
  playing,
}
