// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_tempo_map`, `ensure_android_context`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// The output devices the platform offers.
///
/// # Errors
/// Returns a message if the platform cannot be queried.
Future<List<AudioDevice>> audioDevices() =>
    RustLib.instance.api.crateApiAudioAudioDevices();

/// Open (or reopen) the output stream.
///
/// # Errors
/// Returns a message if the device cannot be opened.
Future<AudioStreamStatus> audioStart({required AudioStreamRequest request}) =>
    RustLib.instance.api.crateApiAudioAudioStart(request: request);

/// Close the output stream.
Future<void> audioStop() => RustLib.instance.api.crateApiAudioAudioStop();

/// The state of the stream currently open, or `None` if there is none.
Future<AudioStreamStatus?> audioStatus() =>
    RustLib.instance.api.crateApiAudioAudioStatus();

/// Switch the reference test tone on or off, and set its frequency and gain.
///
/// `amplitude` is linear gain in `0.0..=1.0`; `frequency_hz` is clamped to the
/// audible range.
Future<void> setTestTone({
  required bool enabled,
  required double frequencyHz,
  required double amplitude,
}) => RustLib.instance.api.crateApiAudioSetTestTone(
  enabled: enabled,
  frequencyHz: frequencyHz,
  amplitude: amplitude,
);

/// Start playing from the current position.
Future<void> transportPlay() =>
    RustLib.instance.api.crateApiAudioTransportPlay();

/// Stop advancing, holding the playhead where it is.
Future<void> transportPause() =>
    RustLib.instance.api.crateApiAudioTransportPause();

/// Stop and return to the stop anchor.
Future<void> transportStop() =>
    RustLib.instance.api.crateApiAudioTransportStop();

/// Move the playhead.
Future<void> transportSeek({required double tick}) =>
    RustLib.instance.api.crateApiAudioTransportSeek(tick: tick);

/// Set the loop region, in ticks.
Future<void> transportSetLoop({
  required BigInt startTick,
  required BigInt endTick,
  required bool enabled,
}) => RustLib.instance.api.crateApiAudioTransportSetLoop(
  startTick: startTick,
  endTick: endTick,
  enabled: enabled,
);

/// Replace the whole tempo map.
///
/// # Errors
/// Returns a message if the markers are empty, out of order, or carry a tempo
/// outside 10–400 bpm.
Future<void> transportSetTempoMap({
  required int ppq,
  required List<TempoMarker> markers,
}) => RustLib.instance.api.crateApiAudioTransportSetTempoMap(
  ppq: ppq,
  markers: markers,
);

/// Set a single constant tempo, keeping the current resolution.
///
/// # Errors
/// Returns a message if `bpm` is outside 10–400.
Future<void> transportSetTempo({required double bpm}) =>
    RustLib.instance.api.crateApiAudioTransportSetTempo(bpm: bpm);

/// Read the playhead. Cheap enough to call once per rendered frame.
TransportPosition transportPosition() =>
    RustLib.instance.api.crateApiAudioTransportPosition();

/// Bandstand's monotonic clock, in nanoseconds.
///
/// The same clock `TransportPosition::host_time_ns` is expressed in.
BigInt monotonicNowNs() => RustLib.instance.api.crateApiAudioMonotonicNowNs();

/// Set the master level.
Future<void> setMasterGain({required double gain}) =>
    RustLib.instance.api.crateApiAudioSetMasterGain(gain: gain);

/// Decode a cached audio file and make it the thing the transport plays.
///
/// Runs the whole decode before answering — it is a worker-thread call, never
/// the UI thread and never the audio thread. Loading stops the transport at
/// the top of the new track and clears any loop left from the previous one.
///
/// # Errors
/// Returns a human-readable message if the file cannot be opened or decoded.
Future<TrackInfo> playerLoad({required String path}) =>
    RustLib.instance.api.crateApiAudioPlayerLoad(path: path);

/// Forget the loaded track and its timeline.
Future<void> playerUnload() => RustLib.instance.api.crateApiAudioPlayerUnload();

/// Set the channel-gain matrix — the isolation control at the heart of the
/// player (the recordings carry bass on one side, piano on the other).
///
/// The four gains are `[left←left, left←right, right←left, right←right]`,
/// row-major by output; each is clamped to `0.0..=1.0` and ramps, so moving
/// between both-sides, left-only and right-only never clicks. Stereo
/// `(1, 0, 0, 1)` passes the recording through; `(0, 1, 0, 1)` puts only the
/// right side on both speakers.
Future<void> playerSetChannelMix({
  required double leftFromLeft,
  required double leftFromRight,
  required double rightFromLeft,
  required double rightFromRight,
}) => RustLib.instance.api.crateApiAudioPlayerSetChannelMix(
  leftFromLeft: leftFromLeft,
  leftFromRight: leftFromRight,
  rightFromLeft: rightFromLeft,
  rightFromRight: rightFromRight,
);

/// An output device the user can choose.
class AudioDevice {
  /// Backend name; also the key used to reopen the device.
  final String name;

  /// Whether this is the system default output.
  final bool isDefault;

  const AudioDevice({required this.name, required this.isDefault});

  @override
  int get hashCode => name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDefault == other.isDefault;
}

/// What to ask the platform for when opening a stream.
class AudioStreamRequest {
  /// Device name, or `None` for the system default.
  final String? deviceName;

  /// Sample rate to request, or `None` to let Bandstand prefer 48 kHz.
  final int? sampleRate;

  /// Buffer size in frames, or `None` for Bandstand's default of 256.
  final int? bufferFrames;

  const AudioStreamRequest({
    this.deviceName,
    this.sampleRate,
    this.bufferFrames,
  });

  static Future<AudioStreamRequest> default_() =>
      RustLib.instance.api.crateApiAudioAudioStreamRequestDefault();

  @override
  int get hashCode =>
      deviceName.hashCode ^ sampleRate.hashCode ^ bufferFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioStreamRequest &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          sampleRate == other.sampleRate &&
          bufferFrames == other.bufferFrames;
}

/// What the platform actually gave us.
class AudioStreamStatus {
  /// Device the stream is running on.
  final String deviceName;

  /// Negotiated sample rate.
  final int sampleRate;

  /// Negotiated channel count.
  final int channels;

  /// Negotiated buffer size in frames, if the backend fixed one.
  final int? bufferFrames;

  /// The device's native sample format.
  final String sampleFormat;

  /// Backend errors since the stream opened. Non-zero means audio dropped.
  final BigInt errorCount;

  /// Audio blocks rendered since the stream opened.
  final BigInt blockCount;

  /// Frames rendered since the stream opened.
  final BigInt frameCount;

  const AudioStreamStatus({
    required this.deviceName,
    required this.sampleRate,
    required this.channels,
    this.bufferFrames,
    required this.sampleFormat,
    required this.errorCount,
    required this.blockCount,
    required this.frameCount,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bufferFrames.hashCode ^
      sampleFormat.hashCode ^
      errorCount.hashCode ^
      blockCount.hashCode ^
      frameCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioStreamStatus &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bufferFrames == other.bufferFrames &&
          sampleFormat == other.sampleFormat &&
          errorCount == other.errorCount &&
          blockCount == other.blockCount &&
          frameCount == other.frameCount;
}

/// A tempo marker: from `tick` onwards, the tempo is `bpm`.
class TempoMarker {
  /// Position in ticks.
  final BigInt tick;

  /// Beats (quarter notes) per minute.
  final double bpm;

  const TempoMarker({required this.tick, required this.bpm});

  @override
  int get hashCode => tick.hashCode ^ bpm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TempoMarker &&
          runtimeType == other.runtimeType &&
          tick == other.tick &&
          bpm == other.bpm;
}

/// A track loaded into the engine, ready to play.
///
/// Durations are milliseconds: on the file timeline a tick is a millisecond,
/// so [`transport_seek`], [`transport_set_loop`] and [`transport_position`]
/// speak the track's time directly (divide ticks by 1000 for the UI).
class TrackInfo {
  /// Duration in milliseconds — also the track's length in ticks.
  final BigInt durationMs;

  /// The source sample rate; the engine reads across rate differences.
  final int sampleRate;

  const TrackInfo({required this.durationMs, required this.sampleRate});

  @override
  int get hashCode => durationMs.hashCode ^ sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackInfo &&
          runtimeType == other.runtimeType &&
          durationMs == other.durationMs &&
          sampleRate == other.sampleRate;
}

/// A coherent read of the playhead, for the UI to extrapolate from.
///
/// This is the shared-atomic readback of §3: no callback, no message, just a
/// direct read of the cell the audio thread publishes into once per block.
class TransportPosition {
  /// Playhead in ticks when the audio thread published.
  final double tick;

  /// Monotonic nanoseconds at which the published block reaches the speakers.
  final BigInt hostTimeNs;

  /// Monotonic nanoseconds at the moment of this read, so Dart can compute
  /// the elapsed time without a second call.
  final BigInt readAtNs;

  /// Transport state.
  final TransportState state;

  /// Increments on every loop wrap.
  final int loopGeneration;

  /// Ticks per nanosecond at `tick`, for extrapolation.
  final double ticksPerNanosecond;

  /// Tempo in effect at `tick`.
  final double bpm;

  /// Ticks per quarter note.
  final int ppq;

  const TransportPosition({
    required this.tick,
    required this.hostTimeNs,
    required this.readAtNs,
    required this.state,
    required this.loopGeneration,
    required this.ticksPerNanosecond,
    required this.bpm,
    required this.ppq,
  });

  @override
  int get hashCode =>
      tick.hashCode ^
      hostTimeNs.hashCode ^
      readAtNs.hashCode ^
      state.hashCode ^
      loopGeneration.hashCode ^
      ticksPerNanosecond.hashCode ^
      bpm.hashCode ^
      ppq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportPosition &&
          runtimeType == other.runtimeType &&
          tick == other.tick &&
          hostTimeNs == other.hostTimeNs &&
          readAtNs == other.readAtNs &&
          state == other.state &&
          loopGeneration == other.loopGeneration &&
          ticksPerNanosecond == other.ticksPerNanosecond &&
          bpm == other.bpm &&
          ppq == other.ppq;
}

/// What the transport is doing.
enum TransportState {
  /// Not playing; playhead parked at the stop anchor.
  stopped,

  /// Not playing; playhead held where it was.
  paused,

  /// Playing.
  playing,
}
